eureka:
  client:
    fetchRegistry: true #유레카 서버로부터 서버리스트를 받아올지 여부
    registerWithEureka: true #유레카 서버에 현재 로컬을 서비스로 등록할지 여부
    service-url:
      defaultZone: http://localhost:8761/eureka/ #유레카 서버의 주소

server:
  port: 8087 
  
spring:
  application:
    name: zipkin-sleuth
  zipkin:
    base-url: http://localhost:9411 # zipkin 서버
  sleuth:
    sampler:
      probability: 1.0 # 1초에 유입되는 request에 대해 얼마만큼의 비율로 수집할지 결정 (1 = 100%)
      
